# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=20, verbose_name='Modelo')),
                ('car_brand', models.CharField(choices=[('Chevrolet', 'CHEVROLET'), ('Ford', 'FORD')], max_length=20, verbose_name='Marca')),
                ('year', models.CharField(max_length=4, verbose_name='A\xf1o')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Autos',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Fecha')),
                ('price', models.IntegerField(null=True, verbose_name='Precio')),
                ('transaction', models.CharField(choices=[('Compra', 'COMPRA'), ('Reparacion', 'REPARACION'), ('Venta', 'VENTA')], max_length=20, verbose_name='Tipo de Transaccion')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cant_transactions', to='concesionaria.Auto', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Transaccion',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
