# Generated by Django 2.0.6 on 2018-06-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='transaction',
            field=models.CharField(choices=[('Compra', 'COMPRA'), ('Venta', 'VENTA'), ('Reparacion', 'REPARACION')], max_length=20, verbose_name='Tipo de Transaccion'),
        ),
    ]
