# Generated by Django 2.0 on 2018-08-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0003_auto_20180622_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='car_state',
            field=models.CharField(choices=[('Usado', 'USADO'), ('Nuevo', 'NUEVO')], max_length=10, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='car_brand',
            field=models.CharField(choices=[('Ford', 'FORD'), ('Chevrolet', 'CHEVROLET')], max_length=20, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='transaction',
            field=models.CharField(choices=[('Compra', 'COMPRA'), ('Reparacion', 'REPARACION'), ('Venta', 'VENTA')], max_length=20, verbose_name='Tipo de Transaccion'),
        ),
    ]
